server:
  port: 8989
  servlet:
    context-path: /yingx
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingx
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  redis:
    host: 192.168.17.15
    port: 6379
    database: 1
  data:
    elasticsearch:
      cluster-nodes: 192.168.17.16:9300
mybatis:
  type-aliases-package: com.baizhi.wy.entity
  mapper-locations: classpath:com/baizhi/wy/mapper/*Mapper.xml
